version: "3"
services: 
    db:
      image: postgres:10.13
      container_name: database
      restart: always
      environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_HOST: postgres
          POSTGRES_DB: chatty
      volumes:
          - ./database_setup/postgres-data.sql:/docker-entrypoint-initdb.d/init.sql
      ports:
          - "5432:5432"
      networks:
          intranet:
              ipv4_address: 10.0.10.102

    web:
      build: .
      container_name: web
      ports:
        - "8080:8080"
      # volumes:
      #   - myshare:/usr/src/app
      links:
        - db
      depends_on:
        - db

      networks:
          intranet:
              ipv4_address: 10.0.10.103


volumes:
    myshare:
        driver: local

networks:
    intranet:
        ipam:
            driver: default
            config:
                - subnet: 10.0.10.0/24
