swagger: "2.0"
info:
  description: "Documentation for the chatty app"
  version: "1.0.0"
  title: "chatty REST API"
host: "localhost:8080"
basePath: "/api/v1"
tags:
- name: "me"
  description: "personal administration"
- name: "users"
  description: "users ?...."

schemes:
- "http"

paths:
  /createUser:
    get:
      tags:
      - "me"
      summary: "Create user"
      description: "Returns a single user"
      produces:
      - "application/json"
      parameters:
      - name: "username"
        in: "query"
        description: "New user username"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/User"
  /me:
    get:
      tags:
      - "me"
      summary: "Get info about my user by api_key"
      description: "Returns a single user"
      produces:
      - "application/json"
      parameters:
      - name: "api_key"
        in: "query"
        description: "Api key"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/User"
  /me/change:
    post:
      tags:
      - "me"
      summary: "Change user data by api_key"
      description: "Returns a single user"
      produces:
      - "application/json"
      parameters:
      - name: "api_key"
        in: "query"
        description: "Api key"
        required: true
        type: "string"
      - name: "username"
        in: "query"
        description: "New username"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/User"

  /getUsers:
    post:
      tags:
      - "users"
      summary: "get"
      description: "Returns a single user"
      produces:
      - "application/json"
      parameters:
      - name: "api_key"
        in: "query"
        description: "Api key"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/UsersList"


definitions:
  User:
    type: "object"
    properties:
      uid:
        type: "integer"
        format: "int64"
      username:
        type: "string"
      api_key:
        type: "string"
  UsersList:
    type: "array"
    items: 
      $ref: "#/definitions/User"